// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAydNSF2PnTDfqM420xjOe48159ETsYnmw',
    appId: '1:71293046014:web:b325ee811a2679759ae9af',
    messagingSenderId: '71293046014',
    projectId: 'echo-chat-app-81698',
    authDomain: 'echo-chat-app-81698.firebaseapp.com',
    storageBucket: 'echo-chat-app-81698.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARmvHtNWQa9NGIpMJDiuZff8UDDizBl3U',
    appId: '1:71293046014:android:329b0cd98676d3349ae9af',
    messagingSenderId: '71293046014',
    projectId: 'echo-chat-app-81698',
    storageBucket: 'echo-chat-app-81698.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn5hsSjd3mDjd5gkSk5t-vy3jQWZiGuZo',
    appId: '1:71293046014:ios:46bbffe882bdb1879ae9af',
    messagingSenderId: '71293046014',
    projectId: 'echo-chat-app-81698',
    storageBucket: 'echo-chat-app-81698.firebasestorage.app',
    iosBundleId: 'com.example.echoApp',
  );
}
